name: Prime Dependency Cache

on:
  workflow_dispatch:
jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: prime-cache-1758ae0
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-1758ae0
